### ISSUE TITLE
一个基于 Teambition + Gitlab + Jenkins 的自动化开发工作流设想

### ISSUE THREAD

**Issue by mofelee** [mofelee/temp-blog#3]
deprecated， 使用etcd实现应该更好

--------

## 背景
在项目的流程越来越复杂的今天，一个项目的完成往往需要依靠多个平台、多组人员相互协作才能完成，但问题在于，通常各个平台给出的接口往往无法满足相互协作的需求（例如：Teambition通知Gitlab创建对应需求分支，Gitlab完成任务后报告的Teambition上），并且很难找到一个能完美适应流程需求，统一调度各个资源的程序。为了更优雅的解决这个问题，借鉴 redux 的思想，设想应该是有一个消息调度中心，这个调度中心负责接收消息，并将这些消息分发到各个已经注册在其上的组件，由组件决定应该执行何种操作。

## 基本原理
针对每个平台设计一个消息适配器，消息适配器会以特定方式接收到应用程序的通知消息，并转换为“核心调度器”规定的格式，核心调度器会将接收到的消息分发到已经注册在其上的其他消息适配器。

![image](https://cloud.githubusercontent.com/assets/5069410/21842840/7fd7e62e-d823-11e6-839e-5c667d0593be.png)

图：程序内部视角，Teambition 上的消息适配器通过 webhook 接收到特定格式的消息，并转换为标准格式后，通过核心调度器分发到各个已经注册的消息适配器，以 Jenkins 为例，消息适配器接收到核心调度器的消息后，转换为调用 Jenkins API 的行为，执行相对应的操作。

**消息适配器**是一个能接收和发送消息的web服务器。消息适配器在后面可能被称为“机器人”，消息适配器由三部分组成：

1. 配置信息层，包括通用的核心调度器地址等信息以及业务相关配置信息；
2. 业务逻辑层（这部分需要coding）；
3. 底层通信库。

**核心调度器**也是一个能接收和发送消息的web服务器，不同之处在于核心控制器主要作用是分发消息，主要由两部分组成。

1. 核心调度器中间件（类似记录日志之类的中间件）；
2. 底层通信库。

注：核心调度器启动不包含配置信息，分发消息时的地址由消息适配器首次连接成功时保存在核心调度器内存中。

**标准的消息格式**参考 https://github.com/acdlite/flux-standard-action

![image](https://cloud.githubusercontent.com/assets/5069410/21875701/ef5b7430-d8b8-11e6-83be-8b39590f61cc.png)
图：外部视角，由nginx向外暴露服务，内部通过socketCluster进行通信，由Docker compose 启动整个服务。

![image](https://cloud.githubusercontent.com/assets/5069410/21876235/53625a90-d8bc-11e6-80fb-e7ec7f8763bb.png)
图：消息适配器内部工作原理，演示了如何与Teambition进行连接

## 消息适配器和核心调度器设计原则
因为涉及调用外部资源比较多，所以系统内部不保证任务一定完全执行成功，也没有类似transaction的操作，只能通过外部服务返回另一个表示成功的消息才能确定。

# 实现

## 工作流设计原则
1. 确保系统的各个部分都能形成闭环，各个人员提出的需求都能收到相关回应。
2. 每个动作都要被确切记录，类似发布测试，发布生产环境等，换种说法就是正常情况下不能通过直接操作代码发布，必须在 Gitlab 或者 Teambition 相应任务下通知机器人完成。
3. 专注于更重要的事情，例如修复一个bug不应该关注太多分支操作和发布操作。

## 开发新需求的场景
1. 产品经理负责在 Teambition 建立拆分任务，并在完成时检查成果是否符合预期；
1. 设计师负责根据产品经理的需求，在Teambition更新设计图；
1. 当需求基本完成时，由 Team Leader 通知机器人需要在Gitlab建立对应的任务，并且Teambition相应任务更新时会同步更新到Gitlab上;
1. 如果有开发人员在 Gitlab 接手了相应任务，自动创建对应的分支（注，未避免流程控制过于复杂，这里的分支必须是可以单独发布的完整功能的分支，如牵扯到其他任务，则说明这个任务是其他任务的子任务，应在Teambition上合并为一个开发任务）；
1. 完成后通知 Jenkins 生成相对应的产物回复到 Gitlab 和 Teambition 上，通知组员进行code review。
1. review 结束后更新状态到 Teambition，并通知测试人员介入；
1. 测试完成后测试可以在 Teambition 通知发布。

开发新需求时各组件的责任：
1. Teambition 负责监控一整个sprint，包括建立需求，需求拆分，并且最后的产物也要报告到teambition
2. Gitlab 负责监控软件开发的周期，譬如建立对应需求的任务，合并分支，code review，发布Relese，跟踪测试报告等等。
3. Jenkins 负责操作 repo，测试，部署。

**Comment by m9aq** [comment]
这个流程有开发么?

**Comment by m9aq** [comment]
这个有开发计划么？

**Comment by mofelee** [comment]
@m9aq 最近没有时间做这个，但是实际上这个方案本来就不够完美
因为我们现在任务必须在teambition上管理。
但是我认为对于程序员来说，Gitlab更适合管理任务
所以即使有谁认为这个方案比较好，我还是不建议去做这样一个工具。

**Comment by m9aq** [comment]
确实是。Gitlab实际上已经有简单的管理工具了。 

    On Tuesday, March 7, 2017 10:39 AM, MofeLee <notifications@github.com> wrote:
 

 @m9aq 最近没有时间做这个，但是实际上这个方案本来就不够完美
因为我们现在任务必须在teambition上管理。
但是我认为对于程序员来说，Gitlab更适合管理任务
所以即使有谁认为这个方案比较好，我还是不建议去做这样一个工具。—

**Comment by JoshYuJump** [comment]
`运营团队：运营，销售，客服` 习惯 Teambition
`产品团队：产品经验，UI ` 也习惯 Teambition
`产品团队：开发` 适用于 Gitlab

**Comment by banpie** [comment]
如果TB开放直接可以在后台配置webhook，在整合进zapier，就很自动化了。

**Comment by qiushile** [comment]
https://apps.teambition.com/app/600e615612d864002f77d344
看了看这个有点像（但是不是
开发了可以发布到钉钉开放平台了
